import "@/styles/globals.css";

import type { Metadata } from "next";

import { onest, pally } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${onest.variable} ${pally.variable}`}>
      <body>{children}</body>
    </html>
  );
}
